# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Derogation
                                 A QGIS plugin
 Cette extension a pour but d'aider à la prise de décision dans le cas de dérogation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-04
        copyright            : (C) 2022 by Mohamed EL BAKKALI
        email                : mmed172017@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Derogation class from file Derogation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .derogation import Derogation
    return Derogation(iface)
